# Common configuration for all profiles
spring:
  profiles:
    active: dev
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3000s
  application:
    name: superhero-proxy

# Server Configuration
server:
  port: 8080  # HTTP port

# SuperHero API Configuration
superhero:
  api:
    url: https://superheroapi.com/api
    token: 1b3bc65ad40627f75f8edcdfbc67831d

    ids:
      url: https://superheroapi.com/ids.html
  cache:
    update:
      interval: 300

#  autoconfigure:
#    exclude: org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration

# gRPC Server Configuration
grpc:
  server:
    port: 9091
    security:
      enabled: false
    netty:
      keep-alive-time: 30
      keep-alive-timeout: 20
      keep-alive-without-calls: true
      max-connection-idle: 10
      max-connection-age: 30
      max-connection-age-grace: 5
      permit-keep-alive-time: 5
      permit-keep-alive-without-calls: true
  client:
    channel:
      host: localhost
      port: 9091
      keep-alive:
        time: 15  # Shorter for faster detection
        timeout: 10  # Shorter timeout for clients
        without-calls: true  # Don't keep idle connections

# Logging Configuration (common for all profiles)
logging:
  file:
    name: logs/superhero-proxy.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.example.superheroproxy: DEBUG
    net.devh.boot.grpc: INFO 