# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod

# gRPC Server Configuration
grpc:
  server:
    port: 9091

# SuperHero API Configuration
superhero:
  api:
    token: 1b3bc65ad40627f75f8edcdfbc67831d  # Use environment variable in production 