# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: dev

# gRPC Server Configuration
grpc:
  server:
    port: 9091

# SuperHero API Configuration
superhero:
  api:
    token: 1b3bc65ad40627f75f8edcdfbc67831d 