# Common configuration for all profiles
spring:
  profiles:
    active: dev
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=20,expireAfterWrite=10m  # 65 minutes expiration

# Server Configuration
server:
  port: 8080  # HTTP port

# SuperHero API Configuration
superhero:
  api:
    url: https://superheroapi.com/api
    token: 1b3bc65ad40627f75f8edcdfbc67831d

  cache:
    update:
      interval: 60  # 1 minute in seconds (test only)

#  autoconfigure:
#    exclude: org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration

# gRPC Server Configuration
grpc:
  server:
    port: 9091
    security:
      enabled: false
    netty:
      keep-alive-time: 30
      keep-alive-timeout: 20
      keep-alive-without-calls: true
      max-connection-idle: 10
      max-connection-age: 30
      max-connection-age-grace: 5
      permit-keep-alive-time: 5
      permit-keep-alive-without-calls: true

# Logging Configuration (common for all profiles)
logging:
  level:
    root: INFO
    com.example.superheroproxy: DEBUG
    net.devh.boot.grpc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 