# Common configuration for all profiles
spring:
  profiles:
    active: dev
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=3000s
  application:
    name: superhero-proxy

# Rate Limiting Configuration
rate:
  limit:
    permits-per-second: 10  # Number of requests allowed per second

# Restful Server Configuration
server:
  port: 8080  # HTTP port

# SuperHero API Configuration
superhero:
  api:
    url: https://superheroapi.com/api
    token: 1b3bc65ad40627f75f8edcdfbc67831d

    ids:
      url: https://superheroapi.com/ids.html
  cache:
    update:
      interval: 300
      initial-delay: 300

#  autoconfigure:
#    exclude: org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration

# gRPC Server Configuration
grpc:
  server:
    port: 9091
    security:
      enabled: false
    netty:
      keep-alive-time: 60
      keep-alive-timeout: 30
      keep-alive-without-calls: false
      max-connection-idle: 120
      max-connection-age: 300
      max-connection-age-grace: 30
      permit-keep-alive-time: 60
      permit-keep-alive-without-calls: false
  client:
    channel:
      host: localhost
      port: 9091
      keep-alive:
        time: 60  # Increased to 60 seconds
        timeout: 30  # Increased to 30 seconds
        without-calls: false  # Disabled keepalive without calls

# Logging Configuration (common for all profiles)
logging:
  file:
    name: logs/superhero-proxy.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.example.superheroproxy: DEBUG
    net.devh.boot.grpc: INFO

# Notification Configuration
notification:
  max-subscribers-per-hero: 1000
  max-total-subscribers: 10000
  cleanup-interval-minutes: 5
  subscriber-timeout-minutes: 30
  notification-thread-pool-size: 10

async:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 100
  thread-name-prefix: "AsyncNotification-" 