spring:
  application:
    name: redis-cache-demo
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 5000
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
      cache-null-values: true
      use-key-prefix: true
      key-prefix: "cache:"

server:
  port: 8080

logging:
  level:
    org.springframework.data.redis: DEBUG
    com.example.redis: DEBUG 